### PR TITLE
Added error checking to the scanner

### PR DESCRIPTION
**Pull request by TrevorKitt**
Scanner no longer returns a vector of tokens. Instead it accepts a
pointer to a vector as input and returns an int as a result code.
Scanner will now throw an error if an invalid token is generated.
Added dfa to consume input for whitespace and control characters.
Added cleanup to free memory on program termination.
Fixed a bug that was causing the scanner to initialize with 0 dfas.

### CODE REVIEW

**Comment by btruhand** [comment]
One thing to remember is that the grammar has no notion of control characters, whitespace and comments, so these should not be given to the parser.

**Comment by TrevorKitt** [comment]
Yup, whenever the scanner finds control characters, whitespace or comments it consumes the input with the appropriate dfa but does not actually generate a token. The input is just discarded. My previous description with the commit was not quite correct.

**Comment by btruhand** [comment]
Oh ya Trevor, about that toParse string, technically what we can do is have the parser check for the kind of token it is and if it's a char/string literal, identifier or a valid number it assumes the appropriate value for each token type e.g a char literal is CHAR for the parser, an identifier is an ID etc. If we're going to check token types we'd then need to make a token type for non-terminals since the parse tree will have tokens, which may be non-terminals, and the parser needs to check for the non-terminals too. Tokens of type non-terminals can just have the actual lexeme (which can be gotten from the rules) to be checked by the parser

**Comment by ericluii** [comment]
rebase - then we'll merge.

**Comment by TrevorKitt** [comment]
should be rebased now

**Pull request merged**
