### PR TITLE
Hierarchy checking even numbers

### PR DESCRIPTION
**Pull request by TrevorKitt**
This should pass all but 1 test

### CODE REVIEW

**Comment by btruhand** [comment]
Which one is it not passing?

**Comment by TrevorKitt** [comment]
One of the tests to check for final methods being hidden. The problem is that I'm comparing method signatures to find out if a method has been overwritten and the method signatures are different.
One has: getRowStart(JTextComponent,int)
The other has: getRowStart(javax.swing.text.JTextComponent,int)

**Comment by TrevorKitt** [comment]
It's Je_4_FinalHide

**Comment by btruhand** [comment]
Ah yea it the function that returns method signature doesn't turn a fully qualified name to a simple name or vice versa. A ReferenceType AST node has a pointer to the compilation table of the type it refers to. The ParamList AST node has a pointer to a Type which may be a PrimitiveType or ReferenceType, which you can check for. Your best bet is probably doing the check through there

**Comment by TrevorKitt** [comment]
I'm getting a segmentation fault when I try to access the 
CompilationTable\* referenceTable
for a reference type. Where should this be set?

**Comment by btruhand** [comment]
Really? it should be set in the type linking part and if it's NULL then compilation stage stops there. How are u using it?

**Comment by TrevorKitt** [comment]
This now passes every test on my machine

**Comment by btruhand** [comment]
Cool! Thanks a lot trevor :D

**Pull request merged**
