### PR TITLE
Error handling cleanup

### PR DESCRIPTION
**Pull request by ericluii**

### CODE REVIEW

**Comment by ericluii** [comment]
Sample error messages from scanner - from running tests:
screen shot 2015-02-05 at 6 47 05 pm

**Comment by ericluii** [comment]
Sample error messages from parsing/weeding - from running tests:
--- obviously, when not running 640 tests, one after another, it will look cleaner. ---
screen shot 2015-02-05 at 7 01 50 pm

**Comment by ericluii** [comment]
@btruhand @TrevorKitt - When this gets merged, I will resubmit to marmoset.

**Comment by btruhand** [comment]
Ayeeeee beautiful, brings tears to my eyes. Kudos eric kudos

**Comment by TrevorKitt** [comment]
It looks great to me!

**Comment by btruhand** [comment]
Lmao seeing how nice it looks, it actually makes me want to handle multiple error reports... But eh sometime later maybe LOL

**Comment by ericluii** [comment]
@TrevorKitt - It's handled!!! check the format

FILENAME:LINE:COLUMN: error: MESSAGE

(:

**Comment by ericluii** [comment]
Changes made

**Pull request merged**
